Repository gisce/amoniak, pull requests merged in 2023-11, with the labels that each got.

#33 Se ha implementado la opción de forzar envío para tarifas a precio indexado
  amoniak/tasks.py
Labels: enhancement

#35 Mejoras en el envío de precios indexados
  amoniak/tasks.py
Labels: enhancement, to be merged :octocat:

#36 Auto release
  .bumpversion.cfg
  .github/workflows/pypi.yml
  .github/workflows/version.yml
Labels: patch, CI

#37 Add long description param setup.py
  setup.py
Labels: patch, CI
